/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostMessagesRouteImport } from './routes/host-messages'
import { Route as HostDashboardRouteImport } from './routes/host-dashboard'
import { Route as HostAddListingRouteImport } from './routes/host-add-listing'
import { Route as HostRouteImport } from './routes/host'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AddListingRouteImport } from './routes/add-listing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as BookingIdRouteImport } from './routes/booking.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostMessagesRoute = HostMessagesRouteImport.update({
  id: '/host-messages',
  path: '/host-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host-dashboard',
  path: '/host-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostAddListingRoute = HostAddListingRouteImport.update({
  id: '/host-add-listing',
  path: '/host-add-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AddListingRoute = AddListingRouteImport.update({
  id: '/add-listing',
  path: '/add-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/host': typeof HostRoute
  '/host-add-listing': typeof HostAddListingRoute
  '/host-dashboard': typeof HostDashboardRoute
  '/host-messages': typeof HostMessagesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wishlist': typeof WishlistRoute
  '/booking/$id': typeof BookingIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/host': typeof HostRoute
  '/host-add-listing': typeof HostAddListingRoute
  '/host-dashboard': typeof HostDashboardRoute
  '/host-messages': typeof HostMessagesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wishlist': typeof WishlistRoute
  '/booking/$id': typeof BookingIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-listing': typeof AddListingRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/host': typeof HostRoute
  '/host-add-listing': typeof HostAddListingRoute
  '/host-dashboard': typeof HostDashboardRoute
  '/host-messages': typeof HostMessagesRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wishlist': typeof WishlistRoute
  '/booking/$id': typeof BookingIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-listing'
    | '/chat'
    | '/dashboard'
    | '/forgot-password'
    | '/host'
    | '/host-add-listing'
    | '/host-dashboard'
    | '/host-messages'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/wishlist'
    | '/booking/$id'
    | '/bookings/$id'
    | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-listing'
    | '/chat'
    | '/dashboard'
    | '/forgot-password'
    | '/host'
    | '/host-add-listing'
    | '/host-dashboard'
    | '/host-messages'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/wishlist'
    | '/booking/$id'
    | '/bookings/$id'
    | '/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/add-listing'
    | '/chat'
    | '/dashboard'
    | '/forgot-password'
    | '/host'
    | '/host-add-listing'
    | '/host-dashboard'
    | '/host-messages'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/verify-otp'
    | '/wishlist'
    | '/booking/$id'
    | '/bookings/$id'
    | '/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddListingRoute: typeof AddListingRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HostRoute: typeof HostRoute
  HostAddListingRoute: typeof HostAddListingRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostMessagesRoute: typeof HostMessagesRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WishlistRoute: typeof WishlistRoute
  BookingIdRoute: typeof BookingIdRoute
  BookingsIdRoute: typeof BookingsIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-messages': {
      id: '/host-messages'
      path: '/host-messages'
      fullPath: '/host-messages'
      preLoaderRoute: typeof HostMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-dashboard': {
      id: '/host-dashboard'
      path: '/host-dashboard'
      fullPath: '/host-dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-add-listing': {
      id: '/host-add-listing'
      path: '/host-add-listing'
      fullPath: '/host-add-listing'
      preLoaderRoute: typeof HostAddListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-listing': {
      id: '/add-listing'
      path: '/add-listing'
      fullPath: '/add-listing'
      preLoaderRoute: typeof AddListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddListingRoute: AddListingRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HostRoute: HostRoute,
  HostAddListingRoute: HostAddListingRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostMessagesRoute: HostMessagesRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WishlistRoute: WishlistRoute,
  BookingIdRoute: BookingIdRoute,
  BookingsIdRoute: BookingsIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
